#!/bin/bash
set -euo pipefail

# ============================================================================
# goog GitHub Action Entrypoint
# ============================================================================

# Move into the working directory (defaults to $GITHUB_WORKSPACE)
WORK_DIR="${INPUT_WORKING_DIRECTORY:-${GITHUB_WORKSPACE:-.}}"
cd "$WORK_DIR"

echo "🖼️  goog — OG Image Generator"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# ============================================================================
# Determine mode and run goog
# ============================================================================

GOOG_EXIT=0

if [ -n "${INPUT_CONFIG:-}" ]; then
    # Batch mode: use JSON config file
    echo "📦 Mode: Batch (config: ${INPUT_CONFIG})"
    goog \
        --config "${INPUT_CONFIG}" \
        --template "${INPUT_TEMPLATE:-templates/og.html}" \
        --workers "${INPUT_WORKERS:-4}" \
        || GOOG_EXIT=$?

elif [ -n "${INPUT_SCAN_MARKDOWN:-}" ]; then
    # Markdown scanning mode
    echo "📝 Mode: Markdown Scan (directory: ${INPUT_SCAN_MARKDOWN})"
    goog \
        --scan-markdown "${INPUT_SCAN_MARKDOWN}" \
        --template "${INPUT_TEMPLATE:-templates/og.html}" \
        --ignore-patterns "${INPUT_IGNORE_PATTERNS:-README.md}" \
        --workers "${INPUT_WORKERS:-4}" \
        || GOOG_EXIT=$?

else
    # Single-image mode
    echo "🎯 Mode: Single Image"

    RAW_FLAG=""
    if [ "${INPUT_RAW:-false}" = "true" ]; then
        RAW_FLAG="--raw"
    fi

    goog \
        --template "${INPUT_TEMPLATE:-templates/og.html}" \
        --title "${INPUT_TITLE:-Hello, Open Graph!}" \
        --desc "${INPUT_DESCRIPTION:-}" \
        --tag "${INPUT_TAG:-Blog Post}" \
        --site "${INPUT_SITE_NAME:-example.com}" \
        --out "${INPUT_OUT:-out/og.png}" \
        --workers "${INPUT_WORKERS:-4}" \
        ${RAW_FLAG} \
        || GOOG_EXIT=$?
fi

if [ "$GOOG_EXIT" -ne 0 ]; then
    echo "❌ goog generation failed with exit code ${GOOG_EXIT}"
    exit "$GOOG_EXIT"
fi

echo "✅ Image generation complete"

# ============================================================================
# Auto-commit generated images
# ============================================================================

if [ "${INPUT_COMMIT:-true}" = "true" ]; then
    echo ""
    echo "📤 Auto-committing generated images..."

    # Configure git for the action
    git config --global user.name "github-actions[bot]"
    git config --global user.email "github-actions[bot]@users.noreply.github.com"

    # Set up authentication
    git remote set-url origin "https://x-access-token:${INPUT_GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"

    # Stage all generated image files
    git add -A "*.png"

    # Check if there are changes to commit
    if git diff --cached --quiet; then
        echo "ℹ️  No changes to commit"
    else
        COMMIT_MSG="${INPUT_COMMIT_MESSAGE:-chore: generate OG images [skip ci]}"
        git commit -m "${COMMIT_MSG}"
        git push
        echo "✅ Changes committed and pushed"
    fi
fi

# ============================================================================
# Post PR preview comment
# ============================================================================

if [ "${INPUT_POST_PREVIEW:-true}" = "true" ] && [ "${GITHUB_EVENT_NAME:-}" = "pull_request" ]; then
    echo ""
    echo "💬 Posting PR preview comment..."

    # Find all generated PNG files
    IMAGES=$(find . -name "*.png" -newer /tmp/goog_start 2>/dev/null || true)

    if [ -n "$IMAGES" ]; then
        # Build the comment body
        COMMENT="## 🖼️ OG Image Preview\n\n"
        COMMENT+="Generated by [goog](https://github.com/riceball-tw/goog)\n\n"

        for img in $IMAGES; do
            # Get relative path
            REL_PATH="${img#./}"
            COMMENT+="### \`${REL_PATH}\`\n"
            COMMENT+="![OG Image](${REL_PATH})\n\n"
        done

        COMMENT+="---\n"
        COMMENT+="_Auto-generated by goog GitHub Action_"

        # Post the comment using gh CLI
        PR_NUMBER=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH" 2>/dev/null || echo "")

        if [ -n "$PR_NUMBER" ]; then
            echo -e "$COMMENT" | gh pr comment "$PR_NUMBER" \
                --repo "$GITHUB_REPOSITORY" \
                --body-file - \
                || echo "⚠️  Failed to post PR comment"
            echo "✅ PR comment posted"
        else
            echo "⚠️  Could not determine PR number, skipping comment"
        fi
    else
        echo "ℹ️  No new images found, skipping PR comment"
    fi
fi

exit 0
